# Generated by Django 5.2 on 2025-07-02 18:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(help_text='PDF file containing the note', upload_to=api.models.note_upload_path, validators=[api.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(help_text='Name/title for this note', max_length=255),
        ),
    ]
