# Generated by Django 5.2.4 on 2025-07-05 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_file_alter_note_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Notion OAuth access token')),
                ('workspace_id', models.CharField(blank=True, help_text='Notion workspace ID', max_length=255, null=True)),
                ('workspace_name', models.CharField(blank=True, help_text='Notion workspace name', max_length=255, null=True)),
                ('bot_id', models.CharField(blank=True, help_text='Notion bot ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notion_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notion Integration',
                'verbose_name_plural': 'Notion Integrations',
            },
        ),
    ]
